<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 2

### 1. Form a 1D array containing elements from -2(including) to 10(excluding) in arithmetic progression with common difference 1.5 , negate all elements which are between 2 and 7, in place. Print out this new array.

In [1]:
import numpy as np
def generate():
    arr = np.arange(-2, 10, 1.5)
    arr[(arr> 2) & (arr < 7)] *= -1
    return arr
generate()

array([-2. , -0.5,  1. , -2.5, -4. , -5.5,  7. ,  8.5])

### 2. Create random vector of size 7 and replace the maximum value by 2 and minimum by 7. Sort this array in reverse order. Return the modified vector.

In [2]:
import numpy as np
def generate():
    random_vector = np.random.random(7)
    random_vector[random_vector.argmax()] = 2
    random_vector[random_vector.argmin()] = 7
    modified_vector = np.array(sorted(random_vector,reverse = True))
    return modified_vector
generate()

array([7.        , 2.        , 0.91841928, 0.80445375, 0.59398142,
       0.59301549, 0.31198231])

### 3. Convert a random 7x2 matrix representing cartesian coordinates to polar coordinates. Print out both.
Hint: use arctan2(). To know more about polar and cartesian coordinates, here's one link:  [polar and cartesian](https://www.mathsisfun.com/polar-cartesian-coordinates.html).

In [3]:
import numpy as np
def generate():
    matrix = np.random.random((7,2))
    row,column = matrix[:,0], matrix[:,1]
    radial_coordinate = np.sqrt(row**2 + column**2)
    angular_coordinate = np.arctan2(column, row)
    print(radial_coordinate)
    print(angular_coordinate) 
    return None
generate()

[0.54152507 0.49456369 1.10897509 0.59550654 0.31781345 0.38059522
 0.69199596]
[0.22056243 0.54043051 0.93044005 0.47768516 1.49911252 0.28460511
 1.1358745 ]


### 4. Create an numpy array sequence named num_seq when only the starting point, step size and length of sequence is given.

In [4]:
import numpy as np

length = 15
start = 5
step = 2

def generate(start, length, step):
    end = start + (step*length)
    num_seq = np.arange(start, end, step)
    return num_seq

generate(start, length, step)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

### 5. Make a 3*3 array using a 1d array of evenly spaced numbers ranging from 0 to 9, name it arr1.<br/> 
### Then transpose it to obtain arr2.  From arr2 subtract a 1*3 array with all elements 1 to get arr4. Return arr4.
HINT: Use reshape and transpose function.

In [5]:
import numpy as np
def generate():
    arr = np.arange(0,9)                                
    arr1 = arr.reshape(3,3) 
    arr2=arr1.transpose()
    arr3=np.ones(3,dtype=int)
    arr4=arr2-arr3
    return arr4
generate()

array([[-1,  2,  5],
       [ 0,  3,  6],
       [ 1,  4,  7]])

### 6. Create a DatetimeIndex that contains each business day of 2016 and use it to index a Series of random numbers. Let's call this Series bus_2k16. Hint: use pd.date_range.

In [6]:
import pandas as pd
import numpy as np
def generate():
    dti = pd.date_range(start='2016-01-01', end='2016-12-31', freq='B') 
    bus_2k16 = pd.Series(np.random.rand(len(dti)), index=dti)
    print(bus_2k16)
generate()

2016-01-01    0.952715
2016-01-04    0.016727
2016-01-05    0.185001
2016-01-06    0.981954
2016-01-07    0.273512
                ...   
2016-12-26    0.401190
2016-12-27    0.720080
2016-12-28    0.810756
2016-12-29    0.694240
2016-12-30    0.811401
Freq: B, Length: 261, dtype: float64


###  7. For each calendar month in dataframe bus_2k16, from previous problem. Print out the mean of values also find the sum of the values in bus_2k16 for every Monday.

In [7]:
import pandas as pd
import numpy as np
def generate():
    dti = pd.date_range(start='2016-01-01', end='2016-12-31', freq='B') 
    bus_2k16 = pd.Series(np.random.rand(len(dti)), index=dti)
    print(bus_2k16)
    print(bus_2k16.resample('M').mean())
    print(bus_2k16[bus_2k16.index.weekday == 0].sum())
    return None
generate()

2016-01-01    0.134090
2016-01-04    0.819109
2016-01-05    0.197624
2016-01-06    0.165091
2016-01-07    0.858171
                ...   
2016-12-26    0.572579
2016-12-27    0.619465
2016-12-28    0.610373
2016-12-29    0.194203
2016-12-30    0.664691
Freq: B, Length: 261, dtype: float64
2016-01-31    0.498652
2016-02-29    0.547004
2016-03-31    0.440244
2016-04-30    0.533383
2016-05-31    0.522054
2016-06-30    0.542855
2016-07-31    0.472698
2016-08-31    0.580922
2016-09-30    0.527462
2016-10-31    0.503242
2016-11-30    0.511233
2016-12-31    0.429924
Freq: M, dtype: float64
29.328696482501464


### 8.Given the dataframe df, In the From_To column split each string on the underscore delimiter _ to give a new temporary DataFrame with the correct values. Also standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".) Assign the correct column names to this temporary DataFrame named as temp. Return temp.

In [11]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
import pandas as pd
def generate():
    temp = df.From_To.str.split('_', expand=True)
    print(temp)
    print(type(temp))
    temp.columns = ['From', 'To']
    temp['From'] = temp['From'].str.capitalize()
    temp['To'] = temp['To'].str.capitalize()
    return temp
generate()

          0          1
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn
<class 'pandas.core.frame.DataFrame'>


From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

### 9. Given a dataFrame with 10 columns of real numbers. Find that column's label which has the smallest sum? Also count the number of unique rows the dataframe has.
Hint: use idxmin method.

In [16]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.random(size=(4, 10)), columns=list('qrstuvwxyz'))
print(df)
def generate():
    print(df.sum().idxmin())
    print(df.drop_duplicates().count())  #for each column in dataframe
    print(df.duplicated().count())  # for whole dataframe
    print(len(df) - df.duplicated(keep=False).sum())
    return None
generate()

          q         r         s         t         u         v         w  \
0  0.673335  0.318018  0.094200  0.242783  0.233655  0.269777  0.853209   
1  0.887917  0.095213  0.046749  0.440201  0.506694  0.076874  0.809851   
2  0.207738  0.822624  0.629993  0.825719  0.465248  0.885489  0.967295   
3  0.451181  0.313585  0.323117  0.451570  0.393657  0.296373  0.259810   

          x         y         z  
0  0.914834  0.628307  0.189183  
1  0.765814  0.965307  0.893304  
2  0.850588  0.075862  0.117012  
3  0.766569  0.926669  0.257706  
s
q    4
r    4
s    4
t    4
u    4
v    4
w    4
x    4
y    4
z    4
dtype: int64
4
4


### 10. Given a dataFrame df with a column 'int' of integers. Print out the dataframe with filtered out rows which contain the same integer as the row immediately above. Also print out the dataframe after subtracting the mean of all integers from each element.
Hint: use drop_duplicates and sub methods

In [15]:
import pandas as pd
df = pd.DataFrame({'int': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def generate():
    print(df.drop_duplicates(subset='int'))
    print(df.sub(df.mean(axis=0), axis=1))
    return None
generate()

   int
0    1
1    2
3    3
4    4
5    5
8    6
9    7
         int
0  -3.272727
1  -2.272727
2  -2.272727
3  -1.272727
4  -0.272727
5   0.727273
6   0.727273
7   0.727273
8   1.727273
9   2.727273
10  2.727273
